### ISSUE TITLE
Compile error. What to do? (Debian testing)

### ISSUE THREAD

**Issue by MegaLite** [cryptozeny/cpuminer-opt-sugarchain#26]
/usr/bin/ld: cpuminer-cpu-miner.o: in function `longpoll_thread':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:2149: undefined reference to `curl_easy_init'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:2268: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: cpuminer-cpu-miner.o: in function `workio_thread':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:1474: undefined reference to `curl_easy_init'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:1511: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: cpuminer-cpu-miner.o: in function `show_version_and_exit':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:2584: undefined reference to `curl_version'
/usr/bin/ld: cpuminer-cpu-miner.o: in function `main':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/cpu-miner.c:3327: undefined reference to `curl_global_init'
/usr/bin/ld: cpuminer-util.o: in function `json_load_url':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:632: undefined reference to `curl_easy_init'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:637: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:638: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:639: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:640: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:641: undefined reference to `curl_easy_setopt'
/usr/bin/ld: cpuminer-util.o:/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:642: more undefined references to `curl_easy_setopt' follow
/usr/bin/ld: cpuminer-util.o: in function `json_load_url':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:656: undefined reference to `curl_easy_perform'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:668: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:652: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:656: undefined reference to `curl_easy_perform'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:654: undefined reference to `curl_easy_setopt'
/usr/bin/ld: cpuminer-util.o: in function `stratum_connect':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1286: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1287: undefined reference to `curl_easy_init'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1310: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1311: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1312: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1313: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1314: undefined reference to `curl_easy_setopt'
/usr/bin/ld: cpuminer-util.o:/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1315: more undefined references to `curl_easy_setopt' follow
/usr/bin/ld: cpuminer-util.o: in function `stratum_connect':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1330: undefined reference to `curl_easy_perform'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1309: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1333: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: cpuminer-util.o: in function `stratum_disconnect':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:1350: undefined reference to `curl_easy_cleanup'
/usr/bin/ld: cpuminer-util.o: in function `json_rpc_call':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:465: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:467: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:469: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:471: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:472: undefined reference to `curl_easy_setopt'
/usr/bin/ld: cpuminer-util.o:/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:473: more undefined references to `curl_easy_setopt' follow
/usr/bin/ld: cpuminer-util.o: in function `json_rpc_call':
/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:512: undefined reference to `curl_slist_append'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:513: undefined reference to `curl_slist_append'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:514: undefined reference to `curl_slist_append'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:515: undefined reference to `curl_slist_append'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:519: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:521: undefined reference to `curl_easy_perform'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:612: undefined reference to `curl_slist_free_all'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:613: undefined reference to `curl_easy_reset'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:485: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:464: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:499: undefined reference to `curl_easy_setopt'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:621: undefined reference to `curl_slist_free_all'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:622: undefined reference to `curl_easy_reset'
/usr/bin/ld: /home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1/util.c:525: undefined reference to `curl_easy_getinfo'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2120: cpuminer] Error 1
make[2]: Leaving directory '/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1'
make[1]: *** [Makefile:6034: all-recursive] Error 1
make[1]: Leaving directory '/home/operator/cpuminer-opt-sugarchain-3.8.8.1.7rc1'
make: *** [Makefile:1161: all] Error 2

**Comment by decryp2kanon** [comment]
will try soon. i guess about some depends on debian.

**Comment by decryp2kanon** [comment]
```
sudo apt-get install -y \
build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zlib1g-dev
```

**Comment by decryp2kanon** [comment]
```bash
sudo apt-get install -y \
build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zlib1g-dev && \
git clone https://github.com/cryptozeny/cpuminer-opt-sugarchain.git && \
cd cpuminer-opt-sugarchain && \
./build-yespower.sh && \
./cpuminer --cputest
```
