### ISSUE TITLE
how can I set build type for Debug mode ?

### ISSUE THREAD

**Issue by EthanHee** [cryptozeny/cpuminer-opt-sugarchain#28]
I can build the source code  On ubuntu 18.04 by the command:./build-yespower.sh
but I  want to build it  On Debug mode.

`how can i make it ?`

**Comment by decryp2kanon** [comment]
```bash
sudo apt-get install -y \
build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zlib1g-dev && \
git clone https://github.com/cryptozeny/cpuminer-opt-sugarchain.git && \
cd cpuminer-opt-sugarchain && \
./build-yespower.sh && \
./cpuminer --cputest
```

**Comment by decryp2kanon** [comment]
> I want to build it On Debug mode.

what do you mean?

**Comment by EthanHee** [comment]
I  want to debug the souce code and set breakpoint by VS code On ubnutu 18.04 .

**Comment by decryp2kanon** [comment]
you may ask there rather than here. its a fork of there.

https://github.com/JayDDee/cpuminer-opt
