### ISSUE TITLE
Mining Xeon E5-2683V3

### ISSUE THREAD

**Issue by iUNeIV** [cryptozeny/cpuminer-opt-sugarchain#29]
Hi,

I have one CPU E5-2683-V3.
I would like to know why when I mine with the CPU with 5 threads I have 500H/s vs 20 threads I have the same hashrate.

**How do I get more hashrate**

**ALGO**: _yescryptR16_
**OS**: _Win10_

![Capture](https://user-images.githubusercontent.com/49255050/98750254-56891380-2372-11eb-9c5c-4df73e64e35b.PNG)

![Capture1](https://user-images.githubusercontent.com/49255050/98750256-57ba4080-2372-11eb-80e4-77d55ad4a3ac.PNG)

**Comment by decryp2kanon** [comment]
hi, this is a fork of cpuminer opt. but we do not support other algo than sugarchain. you may ask there. thanks!

https://github.com/JayDDee/cpuminer-opt
